### ISSUE TITLE
Missing pages after Installation

### ISSUE THREAD

**Issue by Domikulka** [thepostcode/nextpost#38]
Hello, I just made a purchase and done every step from the installation process. As I finished it I went to the newly created website and now I can not log in or sign up. When I click on log in im getting this error File not found (404 error).
What I have to do? Thanks
![npproblem](https://user-images.githubusercontent.com/36892547/36737220-dbfc6c8a-1bda-11e8-91e6-913bea0287e0.png)
![npprblem2](https://user-images.githubusercontent.com/36892547/36737233-e2200f7c-1bda-11e8-8aba-e0d179f6ad48.png)

**Comment by alper-mf** [comment]
Hi, You must be add .htaccess file your hosting account.

**Comment by homyo9** [comment]
@Domikulka If your index.php file is loading properly on your php script but other pages are not this likely indicates an issue with your url redirects. On apache these are likely to be located in an .htaccess file in your web root.

In order for the redirects included in the .htaccess file to be used by Apache to route requests you need to ensure that your virtualhost configuration for this site uses:

AllowOverride All
rather than the default

AllowOverride None
This tells apache that it can use directives in the .htaccess file to override the default settings.

**Comment by ntgentil** [comment]
I have the same problem, and my .htaccess are correct what should I do?

**Comment by homyo9** [comment]
@ntgentil You're on VPS?

**Comment by ntgentil** [comment]
Panel Plesk

**Comment by icecreamdigital** [comment]
Did anyone find a solution?

My .htaccess are correct too and now the author doesn't provide support not sure where to go.

After installation all of the links return 404 error.

**Comment by homyo9** [comment]
@icecreamdigital you're using VPS?

**Comment by icecreamdigital** [comment]
Yep

**Comment by homyo9** [comment]
Ubuntu or CentOS?

**Comment by icecreamdigital** [comment]
Redhat CentOS

**Comment by homyo9** [comment]
Don't have idea of Redhat CentOS, I can help you regarding Ubuntu 16.04

**Comment by icecreamdigital** [comment]
Thanks dude appreciate it, going to install it on a droplet on digital ocean and see how it goes. You recommend using 16.04 over 18.x?

**Comment by homyo9** [comment]
Don't go for 18.x as it has PHP 7.2 which is buggy!
